name: Deploy2

on:
  push:
    paths:
      - .github/workflows/main.yml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "brittanys30" --password-stdin
        docker image build -t brittanys30/devengine:v2 .
        docker push brittanys30/devengine:v2
